### ISSUE TITLE
Internal Task List of Greek Translation

### ISSUE THREAD

**Issue by dstrants** [dstrants/StateOfJS#1]
## Note
Below  you can find the tasks lists from the original monorepo. Feel free to mention yourself next to the task you have already done or you wish to do!

### User Interface

- [x] General @dstrants 
- [x] Opinions @dstrants 
- [x] Generic Opinions @dstrants 
- [x] Salary Ranges @dstrants 
- [x] Company Size @dstrants 
- [x] Years of Experience @dstrants 
- [x] Sections @dstrants 
- [ ] Tools
- [ ] Pages
- [ ] Blocks
- [ ] Reasons
- [ ] Quadrant
- [ ] Awards
- [ ] Sharing

### Introductions

- [ ] Awards
- [ ] Back-end Frameworks
- [ ] Connections
- [ ] Data Layer
- [ ] Demographics
- [ ] Front-end Frameworks
- [ ] Introduction
- [ ] Flavors
- [ ] Mobile & Desktop
- [ ] Opinions
- [ ] Other Tools
- [ ] Testing

### Conclusions

- [ ] Back-end Frameworks
- [ ] Conclusion
- [ ] Data Layer
- [ ] Front-end Frameworks
- [ ] Flavors
- [ ] Mobile & Desktop
- [ ] Testing
